/**
 * Application Constants & Machine-Readable Error Codes
 */
const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION'
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  FORBIDDEN_RESOURCE: 'FORBIDDEN_RESOURCE',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  EXECUTION_DISABLED: 'EXECUTION_DISABLED',
  MAINNET_BLOCKED: 'MAINNET_BLOCKED',
  RPC_UNAVAILABLE: 'RPC_UNAVAILABLE',
  EXECUTION_TIMEOUT: 'EXECUTION_TIMEOUT',
  DUPLICATE_EXECUTION: 'DUPLICATE_EXECUTION',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  RISK_BLOCKED: 'RISK_BLOCKED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

module.exports = {
  ROLES,
  USER_STATUS,
  HTTP_STATUS,
  ERROR_CODES
};
